backend:
  name: github
  repo: mcironlung/eleventy-base-clean

media_folder: "src/media"
public_folder: "/media"

collections:
  posts:
    folder: "src/posts"
    format: "markdown"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image", name: "image", widget: "image" }
  pages:
    folder: "src/pages"
    format: "html"
  site:
    label: "Site Settings"
    files:
      - file: "src/data/site.js"
        label: "Site Metadata"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Site URL", name: "url", widget: "string" }
          - { label: "Language", name: "language", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image" }
          - { label: "Author Name", name: "authorName", widget: "string" }
          - { label: "Author Email", name: "authorEmail", widget: "string" }
          - { label: "Author URL", name: "authorUrl", widget: "string" }
          - { label: "Default Image", name: "defaultImage", widget: "image" }